version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
            - ./server/nodemon.json:/app/nodemon.json
        ports:
            - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
        command: npm run dev
    client: 
        build: 
            context: ./client
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./client:/app
            - /app/node_modules  
        ports:
            - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
        depends_on:
            - server
        command: npm start