version: '3'
services:
    db:
        image: postgres:12
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app/server
            - ./server/nodemon.json:/app/server/nodemon.json
            - /app/server/node_modules 
        ports:
            - $SERVER_LOCAL_PORT:$SERVER_DOCKER_PORT
        expose:
            - $SERVER_DOCKER_PORT
        depends_on:
            - db
        environment:
            - POSTGRES_DB=$POSTGRES_DB
            - POSTGRES_USER=$POSTGRES_USER
            - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
            - POSTGRES_HOST=$POSTGRES_HOST
    client: 
        build: 
            context: ./client
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./client:/app/client
            - /app/client/node_modules  
        ports:
            - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
        expose:
            - $CLIENT_DOCKER_PORT
        links:
            - server