version: '3'
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - ./server:/app
            - ./server/nodemon.json:/app/nodemon.json
        ports:
            - 9000:9000
        command: npm run dev
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
        volumes:
            - ./client:/app
            - /app/node_modules  
        ports:
            - 3000:3000
        depends_on:
            - server
        command: npm start